[supervisord]
# 在前台运行，这样容器就不会退出
nodaemon=true
user=root
# 将主日志输出到标准输出，方便在 Northflank 控制台查看
logfile=/dev/stdout
logfile_maxbytes=0

[program:loftgw]
command=/app/loftgw
directory=/app
autostart=true
# 核心机制：挂了自动拉起
autorestart=true
# 将错误和标准输出重定向到容器的标准流
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:cloudflared]
# Supervisord 原生支持读取环境变量，语法是 %(ENV_变量名)s
command=/app/cloudflared tunnel --no-autoupdate run --token %(ENV_tunnelid)s
directory=/app
autostart=true
# 核心机制：挂了自动拉起
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
